### ISSUE TITLE
Swift Port?

### ISSUE THREAD

**Issue by chamrc** [couchdeveloper/RXPromise#27]
Any plan to make an implementation of RXPromise in Swift? I can help with this if you would like.

**Comment by couchdeveloper** [comment]
A Futures and Promises library in pure Swift is now available: [FutureLib](https://github.com/couchdeveloper/FutureLib)

**Comment by onmyway133** [comment]
@couchdeveloper Congrats on your FutureLib
BTW, I just implemented Promise A+ in Swift, called [Then](https://github.com/onmyway133/Then)

**Comment by couchdeveloper** [comment]
Thank you very much :)
In fact, porting Objective-C with C++ code is hard to accomplish. But Swift opens new ways to approach problems and it is not like Objective-C, not like JavaScript and not like C++. Thus FutureLib inherited the API and its architecture from Scala and implementation details are solved with GCD as in RXPromise. The cancellation concept has been long discussed in Promise A+ spec, but honestly, I wasn't convinced. Finally, I felt confident that an approach like in the TPL using cancellation tokens was the most powerful and most flexible way to solve this problem. I think you can do everything with FutureLib what you can do with RXPromise - and much more. ;)
